name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - v*
  pull_request:
    branches: [ "main" ]

jobs:
  main:
    name: Run HSIRS Tests
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - uses: psf/black@stable
      - run: pip install -e .
      - run: python -m unittest -v
      - run: python -m olimp.precompensation.nn.train.train --update-schema
